# TCL File Generated by Component Editor 18.1
# Mon Jun 07 10:32:36 CEST 2021
# DO NOT MODIFY


# 
# ipbus_avallon_master "ipbus_avallon_master" v1.0
# E. Plaige 2021.06.07.10:32:36
# Maitre avallon piloté par l'ipbus
# 

# 
# request TCL package from ACDS 18.1
# 
package require -exact qsys 18.1


# 
# module ipbus_avallon_master
# 
set_module_property DESCRIPTION "Maitre avallon piloté par l'ipbus"
set_module_property NAME ipbus_avallon_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "E. Plaige"
set_module_property DISPLAY_NAME ipbus_avallon_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ipbus_avallon_master_0
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ipbus_avallon_master_v4.vhd VHDL PATH ipbus_avallon_master_v4.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter clockrate STRING "70 MHz" ""
set_parameter_property clockrate DEFAULT_VALUE "70 MHz"
set_parameter_property clockrate DISPLAY_NAME clockrate
set_parameter_property clockrate WIDTH ""
set_parameter_property clockrate UNITS None
set_parameter_property clockrate DESCRIPTION ""
set_parameter_property clockrate HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avm_m0
# 
add_interface avm_m0 avalon start
set_interface_property avm_m0 addressGroup 0
set_interface_property avm_m0 addressUnits SYMBOLS
set_interface_property avm_m0 associatedClock clock
set_interface_property avm_m0 associatedReset reset
set_interface_property avm_m0 bitsPerSymbol 8
set_interface_property avm_m0 burstOnBurstBoundariesOnly false
set_interface_property avm_m0 burstcountUnits WORDS
set_interface_property avm_m0 doStreamReads false
set_interface_property avm_m0 doStreamWrites false
set_interface_property avm_m0 holdTime 0
set_interface_property avm_m0 linewrapBursts false
set_interface_property avm_m0 maximumPendingReadTransactions 0
set_interface_property avm_m0 maximumPendingWriteTransactions 0
set_interface_property avm_m0 minimumResponseLatency 1
set_interface_property avm_m0 readLatency 0
set_interface_property avm_m0 readWaitTime 1
set_interface_property avm_m0 setupTime 0
set_interface_property avm_m0 timingUnits Cycles
set_interface_property avm_m0 waitrequestAllowance 0
set_interface_property avm_m0 writeWaitTime 0
set_interface_property avm_m0 ENABLED true
set_interface_property avm_m0 EXPORT_OF ""
set_interface_property avm_m0 PORT_NAME_MAP ""
set_interface_property avm_m0 CMSIS_SVD_VARIABLES ""
set_interface_property avm_m0 SVD_ADDRESS_GROUP ""
set_interface_property avm_m0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port avm_m0 avm_m0_address address Output 32
add_interface_port avm_m0 avm_m0_read read Output 1
add_interface_port avm_m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port avm_m0 avm_m0_readdata readdata Input 32
add_interface_port avm_m0 avm_m0_readdatavalid readdatavalid Input 1
add_interface_port avm_m0 avm_m0_write write Output 1
add_interface_port avm_m0 avm_m0_writedata writedata Output 32


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point inr_irq0
# 
add_interface inr_irq0 interrupt start
set_interface_property inr_irq0 associatedAddressablePoint avm_m0
set_interface_property inr_irq0 associatedClock clock
set_interface_property inr_irq0 associatedReset reset
set_interface_property inr_irq0 irqScheme INDIVIDUAL_REQUESTS
set_interface_property inr_irq0 ENABLED true
set_interface_property inr_irq0 EXPORT_OF ""
set_interface_property inr_irq0 PORT_NAME_MAP ""
set_interface_property inr_irq0 CMSIS_SVD_VARIABLES ""
set_interface_property inr_irq0 SVD_ADDRESS_GROUP ""
set_interface_property inr_irq0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port inr_irq0 inr_irq0_irq irq Input 32


# 
# connection point ipbRead
# 
add_interface ipbRead conduit end
set_interface_property ipbRead associatedClock ""
set_interface_property ipbRead associatedReset ""
set_interface_property ipbRead ENABLED true
set_interface_property ipbRead EXPORT_OF ""
set_interface_property ipbRead PORT_NAME_MAP ""
set_interface_property ipbRead CMSIS_SVD_VARIABLES ""
set_interface_property ipbRead SVD_ADDRESS_GROUP ""
set_interface_property ipbRead IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ipbRead ipb_rdata ipbus_read_readdata Output 32
add_interface_port ipbRead ipb_ack ipbus_read_ack Output 1
add_interface_port ipbRead ipb_err ipbus_read_err Output 1


# 
# connection point IpbusWrite
# 
add_interface IpbusWrite conduit end
set_interface_property IpbusWrite associatedClock ""
set_interface_property IpbusWrite associatedReset ""
set_interface_property IpbusWrite ENABLED true
set_interface_property IpbusWrite EXPORT_OF ""
set_interface_property IpbusWrite PORT_NAME_MAP ""
set_interface_property IpbusWrite CMSIS_SVD_VARIABLES ""
set_interface_property IpbusWrite SVD_ADDRESS_GROUP ""
set_interface_property IpbusWrite IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port IpbusWrite ipb_addr ipbus_write_addr Input 32
add_interface_port IpbusWrite ipb_wdata ipbus_write_writedata Input 32
add_interface_port IpbusWrite ipb_strobe ipbus_write_strobe Input 1
add_interface_port IpbusWrite ipb_write ipbus_write_write Input 1

